name: snowflake-devops-demo

on:
  push:
    branches:
      - main
      - DEV
      - UAT
      - PROD
    paths:
      - 'migrations/**'

  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets['SF_ACCOUNT_' + (github.ref == 'refs/heads/DEV' && 'DEV' || github.ref == 'refs/heads/UAT' && 'UAT' || 'PROD')] }}
          SF_USERNAME: ${{ secrets['SF_USERNAME_' + (github.ref == 'refs/heads/DEV' && 'DEV' || github.ref == 'refs/heads/UAT' && 'UAT' || 'PROD')] }}
          SF_ROLE: ${{ secrets['SF_ROLE_' + (github.ref == 'refs/heads/DEV' && 'DEV' || github.ref == 'refs/heads/UAT' && 'UAT' || 'PROD')] }}
          SF_WAREHOUSE: ${{ secrets['SF_WAREHOUSE_' + (github.ref == 'refs/heads/DEV' && 'DEV' || github.ref == 'refs/heads/UAT' && 'UAT' || 'PROD')] }}
          SF_DATABASE: ${{ secrets['SF_DATABASE_' + (github.ref == 'refs/heads/DEV' && 'DEV' || github.ref == 'refs/heads/UAT' && 'UAT' || 'PROD')] }}
          SNOWFLAKE_PASSWORD: ${{ secrets['SF_PASSWORD_' + (github.ref == 'refs/heads/DEV' && 'DEV' || github.ref == 'refs/heads/UAT' && 'UAT' || 'PROD')] }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table  
